// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: proto/statistics/statistics.proto

package statspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopService) Reset() {
	*x = TopService{}
	mi := &file_proto_statistics_statistics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopService) ProtoMessage() {}

func (x *TopService) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_statistics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopService.ProtoReflect.Descriptor instead.
func (*TopService) Descriptor() ([]byte, []int) {
	return file_proto_statistics_statistics_proto_rawDescGZIP(), []int{0}
}

func (x *TopService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TopService) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DoctorAvgVisit struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Doctor          string                 `protobuf:"bytes,1,opt,name=doctor,proto3" json:"doctor,omitempty"`
	AvgWeeklyVisits float32                `protobuf:"fixed32,2,opt,name=avg_weekly_visits,json=avgWeeklyVisits,proto3" json:"avg_weekly_visits,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DoctorAvgVisit) Reset() {
	*x = DoctorAvgVisit{}
	mi := &file_proto_statistics_statistics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoctorAvgVisit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorAvgVisit) ProtoMessage() {}

func (x *DoctorAvgVisit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_statistics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorAvgVisit.ProtoReflect.Descriptor instead.
func (*DoctorAvgVisit) Descriptor() ([]byte, []int) {
	return file_proto_statistics_statistics_proto_rawDescGZIP(), []int{1}
}

func (x *DoctorAvgVisit) GetDoctor() string {
	if x != nil {
		return x.Doctor
	}
	return ""
}

func (x *DoctorAvgVisit) GetAvgWeeklyVisits() float32 {
	if x != nil {
		return x.AvgWeeklyVisits
	}
	return 0
}

type DoctorAvgVisitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Visits        []*DoctorAvgVisit      `protobuf:"bytes,1,rep,name=visits,proto3" json:"visits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoctorAvgVisitResponse) Reset() {
	*x = DoctorAvgVisitResponse{}
	mi := &file_proto_statistics_statistics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoctorAvgVisitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorAvgVisitResponse) ProtoMessage() {}

func (x *DoctorAvgVisitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_statistics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorAvgVisitResponse.ProtoReflect.Descriptor instead.
func (*DoctorAvgVisitResponse) Descriptor() ([]byte, []int) {
	return file_proto_statistics_statistics_proto_rawDescGZIP(), []int{2}
}

func (x *DoctorAvgVisitResponse) GetVisits() []*DoctorAvgVisit {
	if x != nil {
		return x.Visits
	}
	return nil
}

type DoctorCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Doctor        string                 `protobuf:"bytes,1,opt,name=doctor,proto3" json:"doctor,omitempty"`
	AvgCheck      float32                `protobuf:"fixed32,2,opt,name=avg_check,json=avgCheck,proto3" json:"avg_check,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoctorCheck) Reset() {
	*x = DoctorCheck{}
	mi := &file_proto_statistics_statistics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoctorCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorCheck) ProtoMessage() {}

func (x *DoctorCheck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_statistics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorCheck.ProtoReflect.Descriptor instead.
func (*DoctorCheck) Descriptor() ([]byte, []int) {
	return file_proto_statistics_statistics_proto_rawDescGZIP(), []int{3}
}

func (x *DoctorCheck) GetDoctor() string {
	if x != nil {
		return x.Doctor
	}
	return ""
}

func (x *DoctorCheck) GetAvgCheck() float32 {
	if x != nil {
		return x.AvgCheck
	}
	return 0
}

type DoctorAvgCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Check         []*DoctorCheck         `protobuf:"bytes,1,rep,name=check,proto3" json:"check,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoctorAvgCheckResponse) Reset() {
	*x = DoctorAvgCheckResponse{}
	mi := &file_proto_statistics_statistics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoctorAvgCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorAvgCheckResponse) ProtoMessage() {}

func (x *DoctorAvgCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_statistics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorAvgCheckResponse.ProtoReflect.Descriptor instead.
func (*DoctorAvgCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_statistics_statistics_proto_rawDescGZIP(), []int{4}
}

func (x *DoctorAvgCheckResponse) GetCheck() []*DoctorCheck {
	if x != nil {
		return x.Check
	}
	return nil
}

type DoctorUniquePatient struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Doctor         string                 `protobuf:"bytes,1,opt,name=doctor,proto3" json:"doctor,omitempty"`
	UniquePatients int32                  `protobuf:"varint,2,opt,name=unique_patients,json=uniquePatients,proto3" json:"unique_patients,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DoctorUniquePatient) Reset() {
	*x = DoctorUniquePatient{}
	mi := &file_proto_statistics_statistics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoctorUniquePatient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorUniquePatient) ProtoMessage() {}

func (x *DoctorUniquePatient) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_statistics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorUniquePatient.ProtoReflect.Descriptor instead.
func (*DoctorUniquePatient) Descriptor() ([]byte, []int) {
	return file_proto_statistics_statistics_proto_rawDescGZIP(), []int{5}
}

func (x *DoctorUniquePatient) GetDoctor() string {
	if x != nil {
		return x.Doctor
	}
	return ""
}

func (x *DoctorUniquePatient) GetUniquePatients() int32 {
	if x != nil {
		return x.UniquePatients
	}
	return 0
}

type DoctorUniquePatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patients      []*DoctorUniquePatient `protobuf:"bytes,1,rep,name=patients,proto3" json:"patients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoctorUniquePatientResponse) Reset() {
	*x = DoctorUniquePatientResponse{}
	mi := &file_proto_statistics_statistics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoctorUniquePatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorUniquePatientResponse) ProtoMessage() {}

func (x *DoctorUniquePatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_statistics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorUniquePatientResponse.ProtoReflect.Descriptor instead.
func (*DoctorUniquePatientResponse) Descriptor() ([]byte, []int) {
	return file_proto_statistics_statistics_proto_rawDescGZIP(), []int{6}
}

func (x *DoctorUniquePatientResponse) GetPatients() []*DoctorUniquePatient {
	if x != nil {
		return x.Patients
	}
	return nil
}

type AgeGroupStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgeGroup      string                 `protobuf:"bytes,1,opt,name=age_group,json=ageGroup,proto3" json:"age_group,omitempty"`
	Percent       float32                `protobuf:"fixed32,2,opt,name=percent,proto3" json:"percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgeGroupStat) Reset() {
	*x = AgeGroupStat{}
	mi := &file_proto_statistics_statistics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgeGroupStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgeGroupStat) ProtoMessage() {}

func (x *AgeGroupStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_statistics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgeGroupStat.ProtoReflect.Descriptor instead.
func (*AgeGroupStat) Descriptor() ([]byte, []int) {
	return file_proto_statistics_statistics_proto_rawDescGZIP(), []int{7}
}

func (x *AgeGroupStat) GetAgeGroup() string {
	if x != nil {
		return x.AgeGroup
	}
	return ""
}

func (x *AgeGroupStat) GetPercent() float32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

type AgeGroupStatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgeGroups     []*AgeGroupStat        `protobuf:"bytes,1,rep,name=age_groups,json=ageGroups,proto3" json:"age_groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgeGroupStatResponse) Reset() {
	*x = AgeGroupStatResponse{}
	mi := &file_proto_statistics_statistics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgeGroupStatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgeGroupStatResponse) ProtoMessage() {}

func (x *AgeGroupStatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_statistics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgeGroupStatResponse.ProtoReflect.Descriptor instead.
func (*AgeGroupStatResponse) Descriptor() ([]byte, []int) {
	return file_proto_statistics_statistics_proto_rawDescGZIP(), []int{8}
}

func (x *AgeGroupStatResponse) GetAgeGroups() []*AgeGroupStat {
	if x != nil {
		return x.AgeGroups
	}
	return nil
}

type FloatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Float         float32                `protobuf:"fixed32,1,opt,name=float,proto3" json:"float,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatResponse) Reset() {
	*x = FloatResponse{}
	mi := &file_proto_statistics_statistics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatResponse) ProtoMessage() {}

func (x *FloatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_statistics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatResponse.ProtoReflect.Descriptor instead.
func (*FloatResponse) Descriptor() ([]byte, []int) {
	return file_proto_statistics_statistics_proto_rawDescGZIP(), []int{9}
}

func (x *FloatResponse) GetFloat() float32 {
	if x != nil {
		return x.Float
	}
	return 0
}

type GetByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdRequest) Reset() {
	*x = GetByIdRequest{}
	mi := &file_proto_statistics_statistics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdRequest) ProtoMessage() {}

func (x *GetByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_statistics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdRequest.ProtoReflect.Descriptor instead.
func (*GetByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_statistics_statistics_proto_rawDescGZIP(), []int{10}
}

func (x *GetByIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDoctorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	SecondName    string                 `protobuf:"bytes,2,opt,name=second_name,json=secondName,proto3" json:"second_name,omitempty"`
	Surname       string                 `protobuf:"bytes,3,opt,name=surname,proto3" json:"surname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDoctorResponse) Reset() {
	*x = GetDoctorResponse{}
	mi := &file_proto_statistics_statistics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDoctorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDoctorResponse) ProtoMessage() {}

func (x *GetDoctorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_statistics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDoctorResponse.ProtoReflect.Descriptor instead.
func (*GetDoctorResponse) Descriptor() ([]byte, []int) {
	return file_proto_statistics_statistics_proto_rawDescGZIP(), []int{11}
}

func (x *GetDoctorResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GetDoctorResponse) GetSecondName() string {
	if x != nil {
		return x.SecondName
	}
	return ""
}

func (x *GetDoctorResponse) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

type AllStatsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TotalPatients        int32                  `protobuf:"varint,1,opt,name=total_patients,json=totalPatients,proto3" json:"total_patients,omitempty"`
	TotalVisits          int32                  `protobuf:"varint,2,opt,name=total_visits,json=totalVisits,proto3" json:"total_visits,omitempty"`
	TopServices          []*TopService          `protobuf:"bytes,3,rep,name=top_services,json=topServices,proto3" json:"top_services,omitempty"`
	DocAvgVisits         []*DoctorAvgVisit      `protobuf:"bytes,4,rep,name=doc_avg_visits,json=docAvgVisits,proto3" json:"doc_avg_visits,omitempty"`
	DoctorCheck          []*DoctorCheck         `protobuf:"bytes,5,rep,name=doctor_check,json=doctorCheck,proto3" json:"doctor_check,omitempty"`
	DoctorPatients       []*DoctorUniquePatient `protobuf:"bytes,6,rep,name=doctor_patients,json=doctorPatients,proto3" json:"doctor_patients,omitempty"`
	AgeGroups            []*AgeGroupStat        `protobuf:"bytes,7,rep,name=age_groups,json=ageGroups,proto3" json:"age_groups,omitempty"`
	NewPatientsThisMonth int32                  `protobuf:"varint,8,opt,name=NewPatientsThisMonth,proto3" json:"NewPatientsThisMonth,omitempty"`
	AvgVisitPerPatient   float32                `protobuf:"fixed32,9,opt,name=AvgVisitPerPatient,proto3" json:"AvgVisitPerPatient,omitempty"`
	TotalIncome          float32                `protobuf:"fixed32,10,opt,name=TotalIncome,proto3" json:"TotalIncome,omitempty"`
	MonthlyIncome        float32                `protobuf:"fixed32,11,opt,name=MonthlyIncome,proto3" json:"MonthlyIncome,omitempty"`
	ClinicAvgCheck       float32                `protobuf:"fixed32,12,opt,name=ClinicAvgCheck,proto3" json:"ClinicAvgCheck,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AllStatsResponse) Reset() {
	*x = AllStatsResponse{}
	mi := &file_proto_statistics_statistics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllStatsResponse) ProtoMessage() {}

func (x *AllStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_statistics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllStatsResponse.ProtoReflect.Descriptor instead.
func (*AllStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_statistics_statistics_proto_rawDescGZIP(), []int{12}
}

func (x *AllStatsResponse) GetTotalPatients() int32 {
	if x != nil {
		return x.TotalPatients
	}
	return 0
}

func (x *AllStatsResponse) GetTotalVisits() int32 {
	if x != nil {
		return x.TotalVisits
	}
	return 0
}

func (x *AllStatsResponse) GetTopServices() []*TopService {
	if x != nil {
		return x.TopServices
	}
	return nil
}

func (x *AllStatsResponse) GetDocAvgVisits() []*DoctorAvgVisit {
	if x != nil {
		return x.DocAvgVisits
	}
	return nil
}

func (x *AllStatsResponse) GetDoctorCheck() []*DoctorCheck {
	if x != nil {
		return x.DoctorCheck
	}
	return nil
}

func (x *AllStatsResponse) GetDoctorPatients() []*DoctorUniquePatient {
	if x != nil {
		return x.DoctorPatients
	}
	return nil
}

func (x *AllStatsResponse) GetAgeGroups() []*AgeGroupStat {
	if x != nil {
		return x.AgeGroups
	}
	return nil
}

func (x *AllStatsResponse) GetNewPatientsThisMonth() int32 {
	if x != nil {
		return x.NewPatientsThisMonth
	}
	return 0
}

func (x *AllStatsResponse) GetAvgVisitPerPatient() float32 {
	if x != nil {
		return x.AvgVisitPerPatient
	}
	return 0
}

func (x *AllStatsResponse) GetTotalIncome() float32 {
	if x != nil {
		return x.TotalIncome
	}
	return 0
}

func (x *AllStatsResponse) GetMonthlyIncome() float32 {
	if x != nil {
		return x.MonthlyIncome
	}
	return 0
}

func (x *AllStatsResponse) GetClinicAvgCheck() float32 {
	if x != nil {
		return x.ClinicAvgCheck
	}
	return 0
}

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_proto_statistics_statistics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_statistics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_proto_statistics_statistics_proto_rawDescGZIP(), []int{13}
}

var File_proto_statistics_statistics_proto protoreflect.FileDescriptor

const file_proto_statistics_statistics_proto_rawDesc = "" +
	"\n" +
	"!proto/statistics/statistics.proto\x12\n" +
	"statistics\x1a\x1fgoogle/protobuf/timestamp.proto\"6\n" +
	"\n" +
	"TopService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"T\n" +
	"\x0eDoctorAvgVisit\x12\x16\n" +
	"\x06doctor\x18\x01 \x01(\tR\x06doctor\x12*\n" +
	"\x11avg_weekly_visits\x18\x02 \x01(\x02R\x0favgWeeklyVisits\"L\n" +
	"\x16DoctorAvgVisitResponse\x122\n" +
	"\x06visits\x18\x01 \x03(\v2\x1a.statistics.DoctorAvgVisitR\x06visits\"B\n" +
	"\vDoctorCheck\x12\x16\n" +
	"\x06doctor\x18\x01 \x01(\tR\x06doctor\x12\x1b\n" +
	"\tavg_check\x18\x02 \x01(\x02R\bavgCheck\"G\n" +
	"\x16DoctorAvgCheckResponse\x12-\n" +
	"\x05check\x18\x01 \x03(\v2\x17.statistics.DoctorCheckR\x05check\"V\n" +
	"\x13DoctorUniquePatient\x12\x16\n" +
	"\x06doctor\x18\x01 \x01(\tR\x06doctor\x12'\n" +
	"\x0funique_patients\x18\x02 \x01(\x05R\x0euniquePatients\"Z\n" +
	"\x1bDoctorUniquePatientResponse\x12;\n" +
	"\bpatients\x18\x01 \x03(\v2\x1f.statistics.DoctorUniquePatientR\bpatients\"E\n" +
	"\fAgeGroupStat\x12\x1b\n" +
	"\tage_group\x18\x01 \x01(\tR\bageGroup\x12\x18\n" +
	"\apercent\x18\x02 \x01(\x02R\apercent\"O\n" +
	"\x14AgeGroupStatResponse\x127\n" +
	"\n" +
	"age_groups\x18\x01 \x03(\v2\x18.statistics.AgeGroupStatR\tageGroups\"%\n" +
	"\rFloatResponse\x12\x14\n" +
	"\x05float\x18\x01 \x01(\x02R\x05float\" \n" +
	"\x0eGetByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"m\n" +
	"\x11GetDoctorResponse\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1f\n" +
	"\vsecond_name\x18\x02 \x01(\tR\n" +
	"secondName\x12\x18\n" +
	"\asurname\x18\x03 \x01(\tR\asurname\"\xec\x04\n" +
	"\x10AllStatsResponse\x12%\n" +
	"\x0etotal_patients\x18\x01 \x01(\x05R\rtotalPatients\x12!\n" +
	"\ftotal_visits\x18\x02 \x01(\x05R\vtotalVisits\x129\n" +
	"\ftop_services\x18\x03 \x03(\v2\x16.statistics.TopServiceR\vtopServices\x12@\n" +
	"\x0edoc_avg_visits\x18\x04 \x03(\v2\x1a.statistics.DoctorAvgVisitR\fdocAvgVisits\x12:\n" +
	"\fdoctor_check\x18\x05 \x03(\v2\x17.statistics.DoctorCheckR\vdoctorCheck\x12H\n" +
	"\x0fdoctor_patients\x18\x06 \x03(\v2\x1f.statistics.DoctorUniquePatientR\x0edoctorPatients\x127\n" +
	"\n" +
	"age_groups\x18\a \x03(\v2\x18.statistics.AgeGroupStatR\tageGroups\x122\n" +
	"\x14NewPatientsThisMonth\x18\b \x01(\x05R\x14NewPatientsThisMonth\x12.\n" +
	"\x12AvgVisitPerPatient\x18\t \x01(\x02R\x12AvgVisitPerPatient\x12 \n" +
	"\vTotalIncome\x18\n" +
	" \x01(\x02R\vTotalIncome\x12$\n" +
	"\rMonthlyIncome\x18\v \x01(\x02R\rMonthlyIncome\x12&\n" +
	"\x0eClinicAvgCheck\x18\f \x01(\x02R\x0eClinicAvgCheck\"\x0e\n" +
	"\fEmptyRequest2Z\n" +
	"\x11StatisticsService\x12E\n" +
	"\vGetAllStats\x12\x18.statistics.EmptyRequest\x1a\x1c.statistics.AllStatsResponseB\x1aZ\x18statistics/proto;statspbb\x06proto3"

var (
	file_proto_statistics_statistics_proto_rawDescOnce sync.Once
	file_proto_statistics_statistics_proto_rawDescData []byte
)

func file_proto_statistics_statistics_proto_rawDescGZIP() []byte {
	file_proto_statistics_statistics_proto_rawDescOnce.Do(func() {
		file_proto_statistics_statistics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_statistics_statistics_proto_rawDesc), len(file_proto_statistics_statistics_proto_rawDesc)))
	})
	return file_proto_statistics_statistics_proto_rawDescData
}

var file_proto_statistics_statistics_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_statistics_statistics_proto_goTypes = []any{
	(*TopService)(nil),                  // 0: statistics.TopService
	(*DoctorAvgVisit)(nil),              // 1: statistics.DoctorAvgVisit
	(*DoctorAvgVisitResponse)(nil),      // 2: statistics.DoctorAvgVisitResponse
	(*DoctorCheck)(nil),                 // 3: statistics.DoctorCheck
	(*DoctorAvgCheckResponse)(nil),      // 4: statistics.DoctorAvgCheckResponse
	(*DoctorUniquePatient)(nil),         // 5: statistics.DoctorUniquePatient
	(*DoctorUniquePatientResponse)(nil), // 6: statistics.DoctorUniquePatientResponse
	(*AgeGroupStat)(nil),                // 7: statistics.AgeGroupStat
	(*AgeGroupStatResponse)(nil),        // 8: statistics.AgeGroupStatResponse
	(*FloatResponse)(nil),               // 9: statistics.FloatResponse
	(*GetByIdRequest)(nil),              // 10: statistics.GetByIdRequest
	(*GetDoctorResponse)(nil),           // 11: statistics.GetDoctorResponse
	(*AllStatsResponse)(nil),            // 12: statistics.AllStatsResponse
	(*EmptyRequest)(nil),                // 13: statistics.EmptyRequest
}
var file_proto_statistics_statistics_proto_depIdxs = []int32{
	1,  // 0: statistics.DoctorAvgVisitResponse.visits:type_name -> statistics.DoctorAvgVisit
	3,  // 1: statistics.DoctorAvgCheckResponse.check:type_name -> statistics.DoctorCheck
	5,  // 2: statistics.DoctorUniquePatientResponse.patients:type_name -> statistics.DoctorUniquePatient
	7,  // 3: statistics.AgeGroupStatResponse.age_groups:type_name -> statistics.AgeGroupStat
	0,  // 4: statistics.AllStatsResponse.top_services:type_name -> statistics.TopService
	1,  // 5: statistics.AllStatsResponse.doc_avg_visits:type_name -> statistics.DoctorAvgVisit
	3,  // 6: statistics.AllStatsResponse.doctor_check:type_name -> statistics.DoctorCheck
	5,  // 7: statistics.AllStatsResponse.doctor_patients:type_name -> statistics.DoctorUniquePatient
	7,  // 8: statistics.AllStatsResponse.age_groups:type_name -> statistics.AgeGroupStat
	13, // 9: statistics.StatisticsService.GetAllStats:input_type -> statistics.EmptyRequest
	12, // 10: statistics.StatisticsService.GetAllStats:output_type -> statistics.AllStatsResponse
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_statistics_statistics_proto_init() }
func file_proto_statistics_statistics_proto_init() {
	if File_proto_statistics_statistics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_statistics_statistics_proto_rawDesc), len(file_proto_statistics_statistics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_statistics_statistics_proto_goTypes,
		DependencyIndexes: file_proto_statistics_statistics_proto_depIdxs,
		MessageInfos:      file_proto_statistics_statistics_proto_msgTypes,
	}.Build()
	File_proto_statistics_statistics_proto = out.File
	file_proto_statistics_statistics_proto_goTypes = nil
	file_proto_statistics_statistics_proto_depIdxs = nil
}
