// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: proto/doctor/doctor.proto

package doctorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Appointment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DoctorId      int32                  `protobuf:"varint,2,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	PatientId     int32                  `protobuf:"varint,5,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	SecondName    string                 `protobuf:"bytes,6,opt,name=second_name,json=secondName,proto3" json:"second_name,omitempty"`
	FirstName     string                 `protobuf:"bytes,7,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	Surname       string                 `protobuf:"bytes,8,opt,name=surname,proto3" json:"surname,omitempty"`
	BirthDate     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Gender        string                 `protobuf:"bytes,10,opt,name=gender,proto3" json:"gender,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,11,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Status        string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Appointment) Reset() {
	*x = Appointment{}
	mi := &file_proto_doctor_doctor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Appointment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Appointment) ProtoMessage() {}

func (x *Appointment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctor_doctor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Appointment.ProtoReflect.Descriptor instead.
func (*Appointment) Descriptor() ([]byte, []int) {
	return file_proto_doctor_doctor_proto_rawDescGZIP(), []int{0}
}

func (x *Appointment) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Appointment) GetDoctorId() int32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

func (x *Appointment) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Appointment) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Appointment) GetPatientId() int32 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *Appointment) GetSecondName() string {
	if x != nil {
		return x.SecondName
	}
	return ""
}

func (x *Appointment) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Appointment) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *Appointment) GetBirthDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

func (x *Appointment) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Appointment) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Appointment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Appointment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Appointment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetTodayAppointmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodayAppointmentsRequest) Reset() {
	*x = GetTodayAppointmentsRequest{}
	mi := &file_proto_doctor_doctor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodayAppointmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodayAppointmentsRequest) ProtoMessage() {}

func (x *GetTodayAppointmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctor_doctor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodayAppointmentsRequest.ProtoReflect.Descriptor instead.
func (*GetTodayAppointmentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_doctor_doctor_proto_rawDescGZIP(), []int{1}
}

func (x *GetTodayAppointmentsRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetUpcomingAppointmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpcomingAppointmentsRequest) Reset() {
	*x = GetUpcomingAppointmentsRequest{}
	mi := &file_proto_doctor_doctor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpcomingAppointmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpcomingAppointmentsRequest) ProtoMessage() {}

func (x *GetUpcomingAppointmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctor_doctor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpcomingAppointmentsRequest.ProtoReflect.Descriptor instead.
func (*GetUpcomingAppointmentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_doctor_doctor_proto_rawDescGZIP(), []int{2}
}

func (x *GetUpcomingAppointmentsRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetUpcomingAppointmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedule      *ScheduleTable         `protobuf:"bytes,1,opt,name=schedule,proto3" json:"schedule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpcomingAppointmentsResponse) Reset() {
	*x = GetUpcomingAppointmentsResponse{}
	mi := &file_proto_doctor_doctor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpcomingAppointmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpcomingAppointmentsResponse) ProtoMessage() {}

func (x *GetUpcomingAppointmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctor_doctor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpcomingAppointmentsResponse.ProtoReflect.Descriptor instead.
func (*GetUpcomingAppointmentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_doctor_doctor_proto_rawDescGZIP(), []int{3}
}

func (x *GetUpcomingAppointmentsResponse) GetSchedule() *ScheduleTable {
	if x != nil {
		return x.Schedule
	}
	return nil
}

type ScheduleTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dates         []string               `protobuf:"bytes,1,rep,name=dates,proto3" json:"dates,omitempty"`
	Times         []string               `protobuf:"bytes,2,rep,name=times,proto3" json:"times,omitempty"`
	Table         []*ScheduleCell        `protobuf:"bytes,3,rep,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleTable) Reset() {
	*x = ScheduleTable{}
	mi := &file_proto_doctor_doctor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleTable) ProtoMessage() {}

func (x *ScheduleTable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctor_doctor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleTable.ProtoReflect.Descriptor instead.
func (*ScheduleTable) Descriptor() ([]byte, []int) {
	return file_proto_doctor_doctor_proto_rawDescGZIP(), []int{4}
}

func (x *ScheduleTable) GetDates() []string {
	if x != nil {
		return x.Dates
	}
	return nil
}

func (x *ScheduleTable) GetTimes() []string {
	if x != nil {
		return x.Times
	}
	return nil
}

func (x *ScheduleTable) GetTable() []*ScheduleCell {
	if x != nil {
		return x.Table
	}
	return nil
}

type ScheduleCell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`               // "01.06.2025"
	Time          string                 `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`               // "09:00"
	Appointment   *UpcomingAppointment   `protobuf:"bytes,3,opt,name=appointment,proto3" json:"appointment,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleCell) Reset() {
	*x = ScheduleCell{}
	mi := &file_proto_doctor_doctor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleCell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleCell) ProtoMessage() {}

func (x *ScheduleCell) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctor_doctor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleCell.ProtoReflect.Descriptor instead.
func (*ScheduleCell) Descriptor() ([]byte, []int) {
	return file_proto_doctor_doctor_proto_rawDescGZIP(), []int{5}
}

func (x *ScheduleCell) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ScheduleCell) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *ScheduleCell) GetAppointment() *UpcomingAppointment {
	if x != nil {
		return x.Appointment
	}
	return nil
}

type UpcomingAppointment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PatientId     int64                  `protobuf:"varint,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	Patient       string                 `protobuf:"bytes,3,opt,name=patient,proto3" json:"patient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpcomingAppointment) Reset() {
	*x = UpcomingAppointment{}
	mi := &file_proto_doctor_doctor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpcomingAppointment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpcomingAppointment) ProtoMessage() {}

func (x *UpcomingAppointment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctor_doctor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpcomingAppointment.ProtoReflect.Descriptor instead.
func (*UpcomingAppointment) Descriptor() ([]byte, []int) {
	return file_proto_doctor_doctor_proto_rawDescGZIP(), []int{6}
}

func (x *UpcomingAppointment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpcomingAppointment) GetPatientId() int64 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *UpcomingAppointment) GetPatient() string {
	if x != nil {
		return x.Patient
	}
	return ""
}

type AppointmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointments  []*Appointment         `protobuf:"bytes,1,rep,name=appointments,proto3" json:"appointments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppointmentsResponse) Reset() {
	*x = AppointmentsResponse{}
	mi := &file_proto_doctor_doctor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppointmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppointmentsResponse) ProtoMessage() {}

func (x *AppointmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctor_doctor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppointmentsResponse.ProtoReflect.Descriptor instead.
func (*AppointmentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_doctor_doctor_proto_rawDescGZIP(), []int{7}
}

func (x *AppointmentsResponse) GetAppointments() []*Appointment {
	if x != nil {
		return x.Appointments
	}
	return nil
}

type TodayAppointment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Time          string                 `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	PatientID     int32                  `protobuf:"varint,4,opt,name=patientID,proto3" json:"patientID,omitempty"`
	Patient       string                 `protobuf:"bytes,5,opt,name=patient,proto3" json:"patient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodayAppointment) Reset() {
	*x = TodayAppointment{}
	mi := &file_proto_doctor_doctor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodayAppointment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodayAppointment) ProtoMessage() {}

func (x *TodayAppointment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctor_doctor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodayAppointment.ProtoReflect.Descriptor instead.
func (*TodayAppointment) Descriptor() ([]byte, []int) {
	return file_proto_doctor_doctor_proto_rawDescGZIP(), []int{8}
}

func (x *TodayAppointment) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TodayAppointment) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *TodayAppointment) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *TodayAppointment) GetPatientID() int32 {
	if x != nil {
		return x.PatientID
	}
	return 0
}

func (x *TodayAppointment) GetPatient() string {
	if x != nil {
		return x.Patient
	}
	return ""
}

type GetTodayAppointmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointments  []*TodayAppointment    `protobuf:"bytes,1,rep,name=appointments,proto3" json:"appointments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodayAppointmentsResponse) Reset() {
	*x = GetTodayAppointmentsResponse{}
	mi := &file_proto_doctor_doctor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodayAppointmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodayAppointmentsResponse) ProtoMessage() {}

func (x *GetTodayAppointmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctor_doctor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodayAppointmentsResponse.ProtoReflect.Descriptor instead.
func (*GetTodayAppointmentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_doctor_doctor_proto_rawDescGZIP(), []int{9}
}

func (x *GetTodayAppointmentsResponse) GetAppointments() []*TodayAppointment {
	if x != nil {
		return x.Appointments
	}
	return nil
}

var File_proto_doctor_doctor_proto protoreflect.FileDescriptor

const file_proto_doctor_doctor_proto_rawDesc = "" +
	"\n" +
	"\x19proto/doctor/doctor.proto\x12\x06doctor\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x04\n" +
	"\vAppointment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tdoctor_id\x18\x02 \x01(\x05R\bdoctorId\x12.\n" +
	"\x04date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12.\n" +
	"\x04time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x05 \x01(\x05R\tpatientId\x12\x1f\n" +
	"\vsecond_name\x18\x06 \x01(\tR\n" +
	"secondName\x12\x1d\n" +
	"\n" +
	"first_name\x18\a \x01(\tR\tfirstName\x12\x18\n" +
	"\asurname\x18\b \x01(\tR\asurname\x129\n" +
	"\n" +
	"birth_date\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tbirthDate\x12\x16\n" +
	"\x06gender\x18\n" +
	" \x01(\tR\x06gender\x12!\n" +
	"\fphone_number\x18\v \x01(\tR\vphoneNumber\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"3\n" +
	"\x1bGetTodayAppointmentsRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"6\n" +
	"\x1eGetUpcomingAppointmentsRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"T\n" +
	"\x1fGetUpcomingAppointmentsResponse\x121\n" +
	"\bschedule\x18\x01 \x01(\v2\x15.doctor.ScheduleTableR\bschedule\"g\n" +
	"\rScheduleTable\x12\x14\n" +
	"\x05dates\x18\x01 \x03(\tR\x05dates\x12\x14\n" +
	"\x05times\x18\x02 \x03(\tR\x05times\x12*\n" +
	"\x05table\x18\x03 \x03(\v2\x14.doctor.ScheduleCellR\x05table\"u\n" +
	"\fScheduleCell\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x12\n" +
	"\x04time\x18\x02 \x01(\tR\x04time\x12=\n" +
	"\vappointment\x18\x03 \x01(\v2\x1b.doctor.UpcomingAppointmentR\vappointment\"^\n" +
	"\x13UpcomingAppointment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\x03R\tpatientId\x12\x18\n" +
	"\apatient\x18\x03 \x01(\tR\apatient\"O\n" +
	"\x14AppointmentsResponse\x127\n" +
	"\fappointments\x18\x01 \x03(\v2\x13.doctor.AppointmentR\fappointments\"\x82\x01\n" +
	"\x10TodayAppointment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x12\n" +
	"\x04time\x18\x03 \x01(\tR\x04time\x12\x1c\n" +
	"\tpatientID\x18\x04 \x01(\x05R\tpatientID\x12\x18\n" +
	"\apatient\x18\x05 \x01(\tR\apatient\"\\\n" +
	"\x1cGetTodayAppointmentsResponse\x12<\n" +
	"\fappointments\x18\x01 \x03(\v2\x18.doctor.TodayAppointmentR\fappointments2\xde\x01\n" +
	"\rDoctorService\x12a\n" +
	"\x14GetTodayAppointments\x12#.doctor.GetTodayAppointmentsRequest\x1a$.doctor.GetTodayAppointmentsResponse\x12j\n" +
	"\x17GetUpcomingAppointments\x12&.doctor.GetUpcomingAppointmentsRequest\x1a'.doctor.GetUpcomingAppointmentsResponseB\x17Z\x15doctor/proto;doctorpbb\x06proto3"

var (
	file_proto_doctor_doctor_proto_rawDescOnce sync.Once
	file_proto_doctor_doctor_proto_rawDescData []byte
)

func file_proto_doctor_doctor_proto_rawDescGZIP() []byte {
	file_proto_doctor_doctor_proto_rawDescOnce.Do(func() {
		file_proto_doctor_doctor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_doctor_doctor_proto_rawDesc), len(file_proto_doctor_doctor_proto_rawDesc)))
	})
	return file_proto_doctor_doctor_proto_rawDescData
}

var file_proto_doctor_doctor_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_doctor_doctor_proto_goTypes = []any{
	(*Appointment)(nil),                     // 0: doctor.Appointment
	(*GetTodayAppointmentsRequest)(nil),     // 1: doctor.GetTodayAppointmentsRequest
	(*GetUpcomingAppointmentsRequest)(nil),  // 2: doctor.GetUpcomingAppointmentsRequest
	(*GetUpcomingAppointmentsResponse)(nil), // 3: doctor.GetUpcomingAppointmentsResponse
	(*ScheduleTable)(nil),                   // 4: doctor.ScheduleTable
	(*ScheduleCell)(nil),                    // 5: doctor.ScheduleCell
	(*UpcomingAppointment)(nil),             // 6: doctor.UpcomingAppointment
	(*AppointmentsResponse)(nil),            // 7: doctor.AppointmentsResponse
	(*TodayAppointment)(nil),                // 8: doctor.TodayAppointment
	(*GetTodayAppointmentsResponse)(nil),    // 9: doctor.GetTodayAppointmentsResponse
	(*timestamppb.Timestamp)(nil),           // 10: google.protobuf.Timestamp
}
var file_proto_doctor_doctor_proto_depIdxs = []int32{
	10, // 0: doctor.Appointment.date:type_name -> google.protobuf.Timestamp
	10, // 1: doctor.Appointment.time:type_name -> google.protobuf.Timestamp
	10, // 2: doctor.Appointment.birth_date:type_name -> google.protobuf.Timestamp
	10, // 3: doctor.Appointment.created_at:type_name -> google.protobuf.Timestamp
	10, // 4: doctor.Appointment.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 5: doctor.GetUpcomingAppointmentsResponse.schedule:type_name -> doctor.ScheduleTable
	5,  // 6: doctor.ScheduleTable.table:type_name -> doctor.ScheduleCell
	6,  // 7: doctor.ScheduleCell.appointment:type_name -> doctor.UpcomingAppointment
	0,  // 8: doctor.AppointmentsResponse.appointments:type_name -> doctor.Appointment
	8,  // 9: doctor.GetTodayAppointmentsResponse.appointments:type_name -> doctor.TodayAppointment
	1,  // 10: doctor.DoctorService.GetTodayAppointments:input_type -> doctor.GetTodayAppointmentsRequest
	2,  // 11: doctor.DoctorService.GetUpcomingAppointments:input_type -> doctor.GetUpcomingAppointmentsRequest
	9,  // 12: doctor.DoctorService.GetTodayAppointments:output_type -> doctor.GetTodayAppointmentsResponse
	3,  // 13: doctor.DoctorService.GetUpcomingAppointments:output_type -> doctor.GetUpcomingAppointmentsResponse
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_doctor_doctor_proto_init() }
func file_proto_doctor_doctor_proto_init() {
	if File_proto_doctor_doctor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_doctor_doctor_proto_rawDesc), len(file_proto_doctor_doctor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_doctor_doctor_proto_goTypes,
		DependencyIndexes: file_proto_doctor_doctor_proto_depIdxs,
		MessageInfos:      file_proto_doctor_doctor_proto_msgTypes,
	}.Build()
	File_proto_doctor_doctor_proto = out.File
	file_proto_doctor_doctor_proto_goTypes = nil
	file_proto_doctor_doctor_proto_depIdxs = nil
}
