// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: proto/doctor/doctor.proto

package doctorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DoctorService_GetTodayAppointments_FullMethodName    = "/doctor.DoctorService/GetTodayAppointments"
	DoctorService_GetUpcomingAppointments_FullMethodName = "/doctor.DoctorService/GetUpcomingAppointments"
)

// DoctorServiceClient is the client API for DoctorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DoctorServiceClient interface {
	GetTodayAppointments(ctx context.Context, in *GetTodayAppointmentsRequest, opts ...grpc.CallOption) (*GetTodayAppointmentsResponse, error)
	GetUpcomingAppointments(ctx context.Context, in *GetUpcomingAppointmentsRequest, opts ...grpc.CallOption) (*GetUpcomingAppointmentsResponse, error)
}

type doctorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDoctorServiceClient(cc grpc.ClientConnInterface) DoctorServiceClient {
	return &doctorServiceClient{cc}
}

func (c *doctorServiceClient) GetTodayAppointments(ctx context.Context, in *GetTodayAppointmentsRequest, opts ...grpc.CallOption) (*GetTodayAppointmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTodayAppointmentsResponse)
	err := c.cc.Invoke(ctx, DoctorService_GetTodayAppointments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorServiceClient) GetUpcomingAppointments(ctx context.Context, in *GetUpcomingAppointmentsRequest, opts ...grpc.CallOption) (*GetUpcomingAppointmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUpcomingAppointmentsResponse)
	err := c.cc.Invoke(ctx, DoctorService_GetUpcomingAppointments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DoctorServiceServer is the server API for DoctorService service.
// All implementations must embed UnimplementedDoctorServiceServer
// for forward compatibility.
type DoctorServiceServer interface {
	GetTodayAppointments(context.Context, *GetTodayAppointmentsRequest) (*GetTodayAppointmentsResponse, error)
	GetUpcomingAppointments(context.Context, *GetUpcomingAppointmentsRequest) (*GetUpcomingAppointmentsResponse, error)
	mustEmbedUnimplementedDoctorServiceServer()
}

// UnimplementedDoctorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDoctorServiceServer struct{}

func (UnimplementedDoctorServiceServer) GetTodayAppointments(context.Context, *GetTodayAppointmentsRequest) (*GetTodayAppointmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTodayAppointments not implemented")
}
func (UnimplementedDoctorServiceServer) GetUpcomingAppointments(context.Context, *GetUpcomingAppointmentsRequest) (*GetUpcomingAppointmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUpcomingAppointments not implemented")
}
func (UnimplementedDoctorServiceServer) mustEmbedUnimplementedDoctorServiceServer() {}
func (UnimplementedDoctorServiceServer) testEmbeddedByValue()                       {}

// UnsafeDoctorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DoctorServiceServer will
// result in compilation errors.
type UnsafeDoctorServiceServer interface {
	mustEmbedUnimplementedDoctorServiceServer()
}

func RegisterDoctorServiceServer(s grpc.ServiceRegistrar, srv DoctorServiceServer) {
	// If the following call pancis, it indicates UnimplementedDoctorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DoctorService_ServiceDesc, srv)
}

func _DoctorService_GetTodayAppointments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTodayAppointmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorServiceServer).GetTodayAppointments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorService_GetTodayAppointments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorServiceServer).GetTodayAppointments(ctx, req.(*GetTodayAppointmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoctorService_GetUpcomingAppointments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUpcomingAppointmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorServiceServer).GetUpcomingAppointments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorService_GetUpcomingAppointments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorServiceServer).GetUpcomingAppointments(ctx, req.(*GetUpcomingAppointmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DoctorService_ServiceDesc is the grpc.ServiceDesc for DoctorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DoctorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "doctor.DoctorService",
	HandlerType: (*DoctorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTodayAppointments",
			Handler:    _DoctorService_GetTodayAppointments_Handler,
		},
		{
			MethodName: "GetUpcomingAppointments",
			Handler:    _DoctorService_GetUpcomingAppointments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/doctor/doctor.proto",
}
