// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: proto/storage/storage.proto

package storagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserRequest) Reset() {
	*x = AddUserRequest{}
	mi := &file_proto_storage_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRequest) ProtoMessage() {}

func (x *AddUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRequest.ProtoReflect.Descriptor instead.
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{0}
}

func (x *AddUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *AddUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AddUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserResponse) Reset() {
	*x = AddUserResponse{}
	mi := &file_proto_storage_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserResponse) ProtoMessage() {}

func (x *AddUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserResponse.ProtoReflect.Descriptor instead.
func (*AddUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{1}
}

func (x *AddUserResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddUserResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AddDoctorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	SecondName    string                 `protobuf:"bytes,3,opt,name=second_name,json=secondName,proto3" json:"second_name,omitempty"`
	Surname       string                 `protobuf:"bytes,4,opt,name=surname,proto3" json:"surname,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Education     string                 `protobuf:"bytes,7,opt,name=education,proto3" json:"education,omitempty"`
	Experience    int32                  `protobuf:"varint,8,opt,name=experience,proto3" json:"experience,omitempty"`
	Gender        string                 `protobuf:"bytes,9,opt,name=gender,proto3" json:"gender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDoctorRequest) Reset() {
	*x = AddDoctorRequest{}
	mi := &file_proto_storage_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDoctorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDoctorRequest) ProtoMessage() {}

func (x *AddDoctorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDoctorRequest.ProtoReflect.Descriptor instead.
func (*AddDoctorRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{2}
}

func (x *AddDoctorRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddDoctorRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *AddDoctorRequest) GetSecondName() string {
	if x != nil {
		return x.SecondName
	}
	return ""
}

func (x *AddDoctorRequest) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *AddDoctorRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *AddDoctorRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AddDoctorRequest) GetEducation() string {
	if x != nil {
		return x.Education
	}
	return ""
}

func (x *AddDoctorRequest) GetExperience() int32 {
	if x != nil {
		return x.Experience
	}
	return 0
}

func (x *AddDoctorRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

type AddDoctorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDoctorResponse) Reset() {
	*x = AddDoctorResponse{}
	mi := &file_proto_storage_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDoctorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDoctorResponse) ProtoMessage() {}

func (x *AddDoctorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDoctorResponse.ProtoReflect.Descriptor instead.
func (*AddDoctorResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{3}
}

func (x *AddDoctorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_storage_storage_proto protoreflect.FileDescriptor

const file_proto_storage_storage_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/storage/storage.proto\x12\astorage\"B\n" +
	"\x0eAddUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"@\n" +
	"\x0fAddUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x94\x02\n" +
	"\x10AddDoctorRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1f\n" +
	"\vsecond_name\x18\x03 \x01(\tR\n" +
	"secondName\x12\x18\n" +
	"\asurname\x18\x04 \x01(\tR\asurname\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x1c\n" +
	"\teducation\x18\a \x01(\tR\teducation\x12\x1e\n" +
	"\n" +
	"experience\x18\b \x01(\x05R\n" +
	"experience\x12\x16\n" +
	"\x06gender\x18\t \x01(\tR\x06gender\")\n" +
	"\x11AddDoctorResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2\x92\x01\n" +
	"\x0eStorageService\x12<\n" +
	"\aAddUser\x12\x17.storage.AddUserRequest\x1a\x18.storage.AddUserResponse\x12B\n" +
	"\tAddDoctor\x12\x19.storage.AddDoctorRequest\x1a\x1a.storage.AddDoctorResponseB\x19Z\x17storage/proto;storagepbb\x06proto3"

var (
	file_proto_storage_storage_proto_rawDescOnce sync.Once
	file_proto_storage_storage_proto_rawDescData []byte
)

func file_proto_storage_storage_proto_rawDescGZIP() []byte {
	file_proto_storage_storage_proto_rawDescOnce.Do(func() {
		file_proto_storage_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_storage_storage_proto_rawDesc), len(file_proto_storage_storage_proto_rawDesc)))
	})
	return file_proto_storage_storage_proto_rawDescData
}

var file_proto_storage_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_storage_storage_proto_goTypes = []any{
	(*AddUserRequest)(nil),    // 0: storage.AddUserRequest
	(*AddUserResponse)(nil),   // 1: storage.AddUserResponse
	(*AddDoctorRequest)(nil),  // 2: storage.AddDoctorRequest
	(*AddDoctorResponse)(nil), // 3: storage.AddDoctorResponse
}
var file_proto_storage_storage_proto_depIdxs = []int32{
	0, // 0: storage.StorageService.AddUser:input_type -> storage.AddUserRequest
	2, // 1: storage.StorageService.AddDoctor:input_type -> storage.AddDoctorRequest
	1, // 2: storage.StorageService.AddUser:output_type -> storage.AddUserResponse
	3, // 3: storage.StorageService.AddDoctor:output_type -> storage.AddDoctorResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_storage_storage_proto_init() }
func file_proto_storage_storage_proto_init() {
	if File_proto_storage_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_storage_storage_proto_rawDesc), len(file_proto_storage_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_storage_storage_proto_goTypes,
		DependencyIndexes: file_proto_storage_storage_proto_depIdxs,
		MessageInfos:      file_proto_storage_storage_proto_msgTypes,
	}.Build()
	File_proto_storage_storage_proto = out.File
	file_proto_storage_storage_proto_goTypes = nil
	file_proto_storage_storage_proto_depIdxs = nil
}
