// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: proto/patient/patient.proto

package patientpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAppointmentSlotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoctorId      int32                  `protobuf:"varint,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppointmentSlotsRequest) Reset() {
	*x = GetAppointmentSlotsRequest{}
	mi := &file_proto_patient_patient_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppointmentSlotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentSlotsRequest) ProtoMessage() {}

func (x *GetAppointmentSlotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patient_patient_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentSlotsRequest.ProtoReflect.Descriptor instead.
func (*GetAppointmentSlotsRequest) Descriptor() ([]byte, []int) {
	return file_proto_patient_patient_proto_rawDescGZIP(), []int{0}
}

func (x *GetAppointmentSlotsRequest) GetDoctorId() int32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

type GetAppointmentSlotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         []*DaySlots            `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppointmentSlotsResponse) Reset() {
	*x = GetAppointmentSlotsResponse{}
	mi := &file_proto_patient_patient_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppointmentSlotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentSlotsResponse) ProtoMessage() {}

func (x *GetAppointmentSlotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patient_patient_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentSlotsResponse.ProtoReflect.Descriptor instead.
func (*GetAppointmentSlotsResponse) Descriptor() ([]byte, []int) {
	return file_proto_patient_patient_proto_rawDescGZIP(), []int{1}
}

func (x *GetAppointmentSlotsResponse) GetSlots() []*DaySlots {
	if x != nil {
		return x.Slots
	}
	return nil
}

type DaySlots struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Slots         []string               `protobuf:"bytes,2,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaySlots) Reset() {
	*x = DaySlots{}
	mi := &file_proto_patient_patient_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaySlots) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaySlots) ProtoMessage() {}

func (x *DaySlots) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patient_patient_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaySlots.ProtoReflect.Descriptor instead.
func (*DaySlots) Descriptor() ([]byte, []int) {
	return file_proto_patient_patient_proto_rawDescGZIP(), []int{2}
}

func (x *DaySlots) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DaySlots) GetSlots() []string {
	if x != nil {
		return x.Slots
	}
	return nil
}

type Appointment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DoctorId      int32                  `protobuf:"varint,2,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	PatientId     int32                  `protobuf:"varint,5,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	SecondName    string                 `protobuf:"bytes,6,opt,name=second_name,json=secondName,proto3" json:"second_name,omitempty"`
	FirstName     string                 `protobuf:"bytes,7,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	Surname       string                 `protobuf:"bytes,8,opt,name=surname,proto3" json:"surname,omitempty"`
	BirthDate     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Gender        string                 `protobuf:"bytes,10,opt,name=gender,proto3" json:"gender,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,11,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Status        string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Appointment) Reset() {
	*x = Appointment{}
	mi := &file_proto_patient_patient_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Appointment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Appointment) ProtoMessage() {}

func (x *Appointment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patient_patient_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Appointment.ProtoReflect.Descriptor instead.
func (*Appointment) Descriptor() ([]byte, []int) {
	return file_proto_patient_patient_proto_rawDescGZIP(), []int{3}
}

func (x *Appointment) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Appointment) GetDoctorId() int32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

func (x *Appointment) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Appointment) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Appointment) GetPatientId() int32 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *Appointment) GetSecondName() string {
	if x != nil {
		return x.SecondName
	}
	return ""
}

func (x *Appointment) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Appointment) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *Appointment) GetBirthDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

func (x *Appointment) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Appointment) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Appointment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Appointment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Appointment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type AddAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointment   *Appointment           `protobuf:"bytes,1,opt,name=appointment,proto3" json:"appointment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAppointmentRequest) Reset() {
	*x = AddAppointmentRequest{}
	mi := &file_proto_patient_patient_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAppointmentRequest) ProtoMessage() {}

func (x *AddAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patient_patient_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAppointmentRequest.ProtoReflect.Descriptor instead.
func (*AddAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_patient_patient_proto_rawDescGZIP(), []int{4}
}

func (x *AddAppointmentRequest) GetAppointment() *Appointment {
	if x != nil {
		return x.Appointment
	}
	return nil
}

type DefaultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefaultResponse) Reset() {
	*x = DefaultResponse{}
	mi := &file_proto_patient_patient_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultResponse) ProtoMessage() {}

func (x *DefaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patient_patient_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultResponse.ProtoReflect.Descriptor instead.
func (*DefaultResponse) Descriptor() ([]byte, []int) {
	return file_proto_patient_patient_proto_rawDescGZIP(), []int{5}
}

type UpcomingAppointments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Time          string                 `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	DoctorId      int32                  `protobuf:"varint,4,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	Doctor        string                 `protobuf:"bytes,5,opt,name=doctor,proto3" json:"doctor,omitempty"`
	Specialty     string                 `protobuf:"bytes,6,opt,name=specialty,proto3" json:"specialty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpcomingAppointments) Reset() {
	*x = UpcomingAppointments{}
	mi := &file_proto_patient_patient_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpcomingAppointments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpcomingAppointments) ProtoMessage() {}

func (x *UpcomingAppointments) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patient_patient_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpcomingAppointments.ProtoReflect.Descriptor instead.
func (*UpcomingAppointments) Descriptor() ([]byte, []int) {
	return file_proto_patient_patient_proto_rawDescGZIP(), []int{6}
}

func (x *UpcomingAppointments) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpcomingAppointments) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *UpcomingAppointments) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *UpcomingAppointments) GetDoctorId() int32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

func (x *UpcomingAppointments) GetDoctor() string {
	if x != nil {
		return x.Doctor
	}
	return ""
}

func (x *UpcomingAppointments) GetSpecialty() string {
	if x != nil {
		return x.Specialty
	}
	return ""
}

type UpdateAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointment   *Appointment           `protobuf:"bytes,1,opt,name=appointment,proto3" json:"appointment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAppointmentRequest) Reset() {
	*x = UpdateAppointmentRequest{}
	mi := &file_proto_patient_patient_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppointmentRequest) ProtoMessage() {}

func (x *UpdateAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patient_patient_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppointmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_patient_patient_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAppointmentRequest) GetAppointment() *Appointment {
	if x != nil {
		return x.Appointment
	}
	return nil
}

type GetUpcomingAppointmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpcomingAppointmentsRequest) Reset() {
	*x = GetUpcomingAppointmentsRequest{}
	mi := &file_proto_patient_patient_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpcomingAppointmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpcomingAppointmentsRequest) ProtoMessage() {}

func (x *GetUpcomingAppointmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patient_patient_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpcomingAppointmentsRequest.ProtoReflect.Descriptor instead.
func (*GetUpcomingAppointmentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_patient_patient_proto_rawDescGZIP(), []int{8}
}

func (x *GetUpcomingAppointmentsRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetUpcomingAppointmentsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Appointments  []*UpcomingAppointments `protobuf:"bytes,1,rep,name=appointments,proto3" json:"appointments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpcomingAppointmentsResponse) Reset() {
	*x = GetUpcomingAppointmentsResponse{}
	mi := &file_proto_patient_patient_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpcomingAppointmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpcomingAppointmentsResponse) ProtoMessage() {}

func (x *GetUpcomingAppointmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patient_patient_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpcomingAppointmentsResponse.ProtoReflect.Descriptor instead.
func (*GetUpcomingAppointmentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_patient_patient_proto_rawDescGZIP(), []int{9}
}

func (x *GetUpcomingAppointmentsResponse) GetAppointments() []*UpcomingAppointments {
	if x != nil {
		return x.Appointments
	}
	return nil
}

type GetByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDRequest) Reset() {
	*x = GetByIDRequest{}
	mi := &file_proto_patient_patient_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDRequest) ProtoMessage() {}

func (x *GetByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patient_patient_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDRequest.ProtoReflect.Descriptor instead.
func (*GetByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_patient_patient_proto_rawDescGZIP(), []int{10}
}

func (x *GetByIDRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetHistoryVisitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryVisitsRequest) Reset() {
	*x = GetHistoryVisitsRequest{}
	mi := &file_proto_patient_patient_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryVisitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryVisitsRequest) ProtoMessage() {}

func (x *GetHistoryVisitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patient_patient_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryVisitsRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryVisitsRequest) Descriptor() ([]byte, []int) {
	return file_proto_patient_patient_proto_rawDescGZIP(), []int{11}
}

func (x *GetHistoryVisitsRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type HistoryVisit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	DoctorId      int32                  `protobuf:"varint,3,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	Doctor        string                 `protobuf:"bytes,4,opt,name=doctor,proto3" json:"doctor,omitempty"`
	Diagnose      string                 `protobuf:"bytes,5,opt,name=diagnose,proto3" json:"diagnose,omitempty"`
	Treatment     string                 `protobuf:"bytes,6,opt,name=treatment,proto3" json:"treatment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryVisit) Reset() {
	*x = HistoryVisit{}
	mi := &file_proto_patient_patient_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryVisit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryVisit) ProtoMessage() {}

func (x *HistoryVisit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patient_patient_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryVisit.ProtoReflect.Descriptor instead.
func (*HistoryVisit) Descriptor() ([]byte, []int) {
	return file_proto_patient_patient_proto_rawDescGZIP(), []int{12}
}

func (x *HistoryVisit) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HistoryVisit) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *HistoryVisit) GetDoctorId() int32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

func (x *HistoryVisit) GetDoctor() string {
	if x != nil {
		return x.Doctor
	}
	return ""
}

func (x *HistoryVisit) GetDiagnose() string {
	if x != nil {
		return x.Diagnose
	}
	return ""
}

func (x *HistoryVisit) GetTreatment() string {
	if x != nil {
		return x.Treatment
	}
	return ""
}

type GetHistoryVisitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Visits        []*HistoryVisit        `protobuf:"bytes,1,rep,name=visits,proto3" json:"visits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryVisitsResponse) Reset() {
	*x = GetHistoryVisitsResponse{}
	mi := &file_proto_patient_patient_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryVisitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryVisitsResponse) ProtoMessage() {}

func (x *GetHistoryVisitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patient_patient_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryVisitsResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryVisitsResponse) Descriptor() ([]byte, []int) {
	return file_proto_patient_patient_proto_rawDescGZIP(), []int{13}
}

func (x *GetHistoryVisitsResponse) GetVisits() []*HistoryVisit {
	if x != nil {
		return x.Visits
	}
	return nil
}

type UploadTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                                // токен авторизации
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`          // имя файла
	FileContent   []byte                 `protobuf:"bytes,3,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"` // содержимое DICOM-файла
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadTestRequest) Reset() {
	*x = UploadTestRequest{}
	mi := &file_proto_patient_patient_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadTestRequest) ProtoMessage() {}

func (x *UploadTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patient_patient_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadTestRequest.ProtoReflect.Descriptor instead.
func (*UploadTestRequest) Descriptor() ([]byte, []int) {
	return file_proto_patient_patient_proto_rawDescGZIP(), []int{14}
}

func (x *UploadTestRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UploadTestRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadTestRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

func (x *UploadTestRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UploadTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"` // UUID созданного документа
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadTestResponse) Reset() {
	*x = UploadTestResponse{}
	mi := &file_proto_patient_patient_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadTestResponse) ProtoMessage() {}

func (x *UploadTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patient_patient_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadTestResponse.ProtoReflect.Descriptor instead.
func (*UploadTestResponse) Descriptor() ([]byte, []int) {
	return file_proto_patient_patient_proto_rawDescGZIP(), []int{15}
}

func (x *UploadTestResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type GetDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // строка, содержащая числовой ID пациента
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentsRequest) Reset() {
	*x = GetDocumentsRequest{}
	mi := &file_proto_patient_patient_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentsRequest) ProtoMessage() {}

func (x *GetDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patient_patient_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentsRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_patient_patient_proto_rawDescGZIP(), []int{16}
}

func (x *GetDocumentsRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Ответ с массивом документов
type GetDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*DocumentInfo        `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentsResponse) Reset() {
	*x = GetDocumentsResponse{}
	mi := &file_proto_patient_patient_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentsResponse) ProtoMessage() {}

func (x *GetDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patient_patient_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentsResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_patient_patient_proto_rawDescGZIP(), []int{17}
}

func (x *GetDocumentsResponse) GetDocuments() []*DocumentInfo {
	if x != nil {
		return x.Documents
	}
	return nil
}

// Информация о документе
type DocumentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                // UUID документа
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`    // Имя файла
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`              // Описание
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Дата создания (формат YYYY-MM-DD HH:MM)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentInfo) Reset() {
	*x = DocumentInfo{}
	mi := &file_proto_patient_patient_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentInfo) ProtoMessage() {}

func (x *DocumentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patient_patient_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentInfo.ProtoReflect.Descriptor instead.
func (*DocumentInfo) Descriptor() ([]byte, []int) {
	return file_proto_patient_patient_proto_rawDescGZIP(), []int{18}
}

func (x *DocumentInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocumentInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *DocumentInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DocumentInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// Запрос на скачивание документа
type DownloadDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"` // UUID документа
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadDocumentRequest) Reset() {
	*x = DownloadDocumentRequest{}
	mi := &file_proto_patient_patient_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadDocumentRequest) ProtoMessage() {}

func (x *DownloadDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patient_patient_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadDocumentRequest.ProtoReflect.Descriptor instead.
func (*DownloadDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_patient_patient_proto_rawDescGZIP(), []int{19}
}

func (x *DownloadDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

// Ответ со скачанным файлом
type DownloadDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`          // Имя файла
	FileContent   []byte                 `protobuf:"bytes,2,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"` // Содержимое файла
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadDocumentResponse) Reset() {
	*x = DownloadDocumentResponse{}
	mi := &file_proto_patient_patient_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadDocumentResponse) ProtoMessage() {}

func (x *DownloadDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patient_patient_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadDocumentResponse.ProtoReflect.Descriptor instead.
func (*DownloadDocumentResponse) Descriptor() ([]byte, []int) {
	return file_proto_patient_patient_proto_rawDescGZIP(), []int{20}
}

func (x *DownloadDocumentResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *DownloadDocumentResponse) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

var File_proto_patient_patient_proto protoreflect.FileDescriptor

const file_proto_patient_patient_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/patient/patient.proto\x12\apatient\x1a\x1fgoogle/protobuf/timestamp.proto\"9\n" +
	"\x1aGetAppointmentSlotsRequest\x12\x1b\n" +
	"\tdoctor_id\x18\x01 \x01(\x05R\bdoctorId\"F\n" +
	"\x1bGetAppointmentSlotsResponse\x12'\n" +
	"\x05slots\x18\x01 \x03(\v2\x11.patient.DaySlotsR\x05slots\"4\n" +
	"\bDaySlots\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05slots\x18\x02 \x03(\tR\x05slots\"\x97\x04\n" +
	"\vAppointment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tdoctor_id\x18\x02 \x01(\x05R\bdoctorId\x12.\n" +
	"\x04date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12.\n" +
	"\x04time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x05 \x01(\x05R\tpatientId\x12\x1f\n" +
	"\vsecond_name\x18\x06 \x01(\tR\n" +
	"secondName\x12\x1d\n" +
	"\n" +
	"first_name\x18\a \x01(\tR\tfirstName\x12\x18\n" +
	"\asurname\x18\b \x01(\tR\asurname\x129\n" +
	"\n" +
	"birth_date\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tbirthDate\x12\x16\n" +
	"\x06gender\x18\n" +
	" \x01(\tR\x06gender\x12!\n" +
	"\fphone_number\x18\v \x01(\tR\vphoneNumber\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"O\n" +
	"\x15AddAppointmentRequest\x126\n" +
	"\vappointment\x18\x01 \x01(\v2\x14.patient.AppointmentR\vappointment\"\x11\n" +
	"\x0fDefaultResponse\"\xa1\x01\n" +
	"\x14UpcomingAppointments\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x12\n" +
	"\x04time\x18\x03 \x01(\tR\x04time\x12\x1b\n" +
	"\tdoctor_id\x18\x04 \x01(\x05R\bdoctorId\x12\x16\n" +
	"\x06doctor\x18\x05 \x01(\tR\x06doctor\x12\x1c\n" +
	"\tspecialty\x18\x06 \x01(\tR\tspecialty\"R\n" +
	"\x18UpdateAppointmentRequest\x126\n" +
	"\vappointment\x18\x01 \x01(\v2\x14.patient.AppointmentR\vappointment\"6\n" +
	"\x1eGetUpcomingAppointmentsRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"d\n" +
	"\x1fGetUpcomingAppointmentsResponse\x12A\n" +
	"\fappointments\x18\x01 \x03(\v2\x1d.patient.UpcomingAppointmentsR\fappointments\" \n" +
	"\x0eGetByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"/\n" +
	"\x17GetHistoryVisitsRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xa1\x01\n" +
	"\fHistoryVisit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x1b\n" +
	"\tdoctor_id\x18\x03 \x01(\x05R\bdoctorId\x12\x16\n" +
	"\x06doctor\x18\x04 \x01(\tR\x06doctor\x12\x1a\n" +
	"\bdiagnose\x18\x05 \x01(\tR\bdiagnose\x12\x1c\n" +
	"\ttreatment\x18\x06 \x01(\tR\ttreatment\"I\n" +
	"\x18GetHistoryVisitsResponse\x12-\n" +
	"\x06visits\x18\x01 \x03(\v2\x15.patient.HistoryVisitR\x06visits\"\x8b\x01\n" +
	"\x11UploadTestRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12!\n" +
	"\ffile_content\x18\x03 \x01(\fR\vfileContent\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"5\n" +
	"\x12UploadTestResponse\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"+\n" +
	"\x13GetDocumentsRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"K\n" +
	"\x14GetDocumentsResponse\x123\n" +
	"\tdocuments\x18\x01 \x03(\v2\x15.patient.DocumentInfoR\tdocuments\"|\n" +
	"\fDocumentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\":\n" +
	"\x17DownloadDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"Z\n" +
	"\x18DownloadDocumentResponse\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12!\n" +
	"\ffile_content\x18\x02 \x01(\fR\vfileContent2\x97\x06\n" +
	"\x0ePatientService\x12`\n" +
	"\x13GetAppointmentSlots\x12#.patient.GetAppointmentSlotsRequest\x1a$.patient.GetAppointmentSlotsResponse\x12J\n" +
	"\x0eAddAppointment\x12\x1e.patient.AddAppointmentRequest\x1a\x18.patient.DefaultResponse\x12l\n" +
	"\x17GetUpcomingAppointments\x12'.patient.GetUpcomingAppointmentsRequest\x1a(.patient.GetUpcomingAppointmentsResponse\x12P\n" +
	"\x11UpdateAppointment\x12!.patient.UpdateAppointmentRequest\x1a\x18.patient.DefaultResponse\x12F\n" +
	"\x11CancelAppointment\x12\x17.patient.GetByIDRequest\x1a\x18.patient.DefaultResponse\x12W\n" +
	"\x10GetHistoryVisits\x12 .patient.GetHistoryVisitsRequest\x1a!.patient.GetHistoryVisitsResponse\x12E\n" +
	"\n" +
	"UploadTest\x12\x1a.patient.UploadTestRequest\x1a\x1b.patient.UploadTestResponse\x12V\n" +
	"\x17GetDocumentsByPatientID\x12\x1c.patient.GetDocumentsRequest\x1a\x1d.patient.GetDocumentsResponse\x12W\n" +
	"\x10DownloadDocument\x12 .patient.DownloadDocumentRequest\x1a!.patient.DownloadDocumentResponseB\x19Z\x17patient/proto;patientpbb\x06proto3"

var (
	file_proto_patient_patient_proto_rawDescOnce sync.Once
	file_proto_patient_patient_proto_rawDescData []byte
)

func file_proto_patient_patient_proto_rawDescGZIP() []byte {
	file_proto_patient_patient_proto_rawDescOnce.Do(func() {
		file_proto_patient_patient_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_patient_patient_proto_rawDesc), len(file_proto_patient_patient_proto_rawDesc)))
	})
	return file_proto_patient_patient_proto_rawDescData
}

var file_proto_patient_patient_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_patient_patient_proto_goTypes = []any{
	(*GetAppointmentSlotsRequest)(nil),      // 0: patient.GetAppointmentSlotsRequest
	(*GetAppointmentSlotsResponse)(nil),     // 1: patient.GetAppointmentSlotsResponse
	(*DaySlots)(nil),                        // 2: patient.DaySlots
	(*Appointment)(nil),                     // 3: patient.Appointment
	(*AddAppointmentRequest)(nil),           // 4: patient.AddAppointmentRequest
	(*DefaultResponse)(nil),                 // 5: patient.DefaultResponse
	(*UpcomingAppointments)(nil),            // 6: patient.UpcomingAppointments
	(*UpdateAppointmentRequest)(nil),        // 7: patient.UpdateAppointmentRequest
	(*GetUpcomingAppointmentsRequest)(nil),  // 8: patient.GetUpcomingAppointmentsRequest
	(*GetUpcomingAppointmentsResponse)(nil), // 9: patient.GetUpcomingAppointmentsResponse
	(*GetByIDRequest)(nil),                  // 10: patient.GetByIDRequest
	(*GetHistoryVisitsRequest)(nil),         // 11: patient.GetHistoryVisitsRequest
	(*HistoryVisit)(nil),                    // 12: patient.HistoryVisit
	(*GetHistoryVisitsResponse)(nil),        // 13: patient.GetHistoryVisitsResponse
	(*UploadTestRequest)(nil),               // 14: patient.UploadTestRequest
	(*UploadTestResponse)(nil),              // 15: patient.UploadTestResponse
	(*GetDocumentsRequest)(nil),             // 16: patient.GetDocumentsRequest
	(*GetDocumentsResponse)(nil),            // 17: patient.GetDocumentsResponse
	(*DocumentInfo)(nil),                    // 18: patient.DocumentInfo
	(*DownloadDocumentRequest)(nil),         // 19: patient.DownloadDocumentRequest
	(*DownloadDocumentResponse)(nil),        // 20: patient.DownloadDocumentResponse
	(*timestamppb.Timestamp)(nil),           // 21: google.protobuf.Timestamp
}
var file_proto_patient_patient_proto_depIdxs = []int32{
	2,  // 0: patient.GetAppointmentSlotsResponse.slots:type_name -> patient.DaySlots
	21, // 1: patient.Appointment.date:type_name -> google.protobuf.Timestamp
	21, // 2: patient.Appointment.time:type_name -> google.protobuf.Timestamp
	21, // 3: patient.Appointment.birth_date:type_name -> google.protobuf.Timestamp
	21, // 4: patient.Appointment.created_at:type_name -> google.protobuf.Timestamp
	21, // 5: patient.Appointment.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 6: patient.AddAppointmentRequest.appointment:type_name -> patient.Appointment
	3,  // 7: patient.UpdateAppointmentRequest.appointment:type_name -> patient.Appointment
	6,  // 8: patient.GetUpcomingAppointmentsResponse.appointments:type_name -> patient.UpcomingAppointments
	12, // 9: patient.GetHistoryVisitsResponse.visits:type_name -> patient.HistoryVisit
	18, // 10: patient.GetDocumentsResponse.documents:type_name -> patient.DocumentInfo
	0,  // 11: patient.PatientService.GetAppointmentSlots:input_type -> patient.GetAppointmentSlotsRequest
	4,  // 12: patient.PatientService.AddAppointment:input_type -> patient.AddAppointmentRequest
	8,  // 13: patient.PatientService.GetUpcomingAppointments:input_type -> patient.GetUpcomingAppointmentsRequest
	7,  // 14: patient.PatientService.UpdateAppointment:input_type -> patient.UpdateAppointmentRequest
	10, // 15: patient.PatientService.CancelAppointment:input_type -> patient.GetByIDRequest
	11, // 16: patient.PatientService.GetHistoryVisits:input_type -> patient.GetHistoryVisitsRequest
	14, // 17: patient.PatientService.UploadTest:input_type -> patient.UploadTestRequest
	16, // 18: patient.PatientService.GetDocumentsByPatientID:input_type -> patient.GetDocumentsRequest
	19, // 19: patient.PatientService.DownloadDocument:input_type -> patient.DownloadDocumentRequest
	1,  // 20: patient.PatientService.GetAppointmentSlots:output_type -> patient.GetAppointmentSlotsResponse
	5,  // 21: patient.PatientService.AddAppointment:output_type -> patient.DefaultResponse
	9,  // 22: patient.PatientService.GetUpcomingAppointments:output_type -> patient.GetUpcomingAppointmentsResponse
	5,  // 23: patient.PatientService.UpdateAppointment:output_type -> patient.DefaultResponse
	5,  // 24: patient.PatientService.CancelAppointment:output_type -> patient.DefaultResponse
	13, // 25: patient.PatientService.GetHistoryVisits:output_type -> patient.GetHistoryVisitsResponse
	15, // 26: patient.PatientService.UploadTest:output_type -> patient.UploadTestResponse
	17, // 27: patient.PatientService.GetDocumentsByPatientID:output_type -> patient.GetDocumentsResponse
	20, // 28: patient.PatientService.DownloadDocument:output_type -> patient.DownloadDocumentResponse
	20, // [20:29] is the sub-list for method output_type
	11, // [11:20] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_patient_patient_proto_init() }
func file_proto_patient_patient_proto_init() {
	if File_proto_patient_patient_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_patient_patient_proto_rawDesc), len(file_proto_patient_patient_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_patient_patient_proto_goTypes,
		DependencyIndexes: file_proto_patient_patient_proto_depIdxs,
		MessageInfos:      file_proto_patient_patient_proto_msgTypes,
	}.Build()
	File_proto_patient_patient_proto = out.File
	file_proto_patient_patient_proto_goTypes = nil
	file_proto_patient_patient_proto_depIdxs = nil
}
